### ISSUE TITLE
Problem compiling the project

### ISSUE THREAD

**Issue by gmile** [robconery/peach#1]
Hi Rob, I can't seem to be able to compile the project with latest elixir/erlang.

In short, this is what I get in return of running `mix deps.compile`:

```
** (Mix) Could not compile dependency :hackney, "/Users/gmile/.mix/rebar3 bare compile --paths "/Users/gmile/projects/peach/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile hackney", update it with "mix deps.update hackney" or clean it with "mix deps.clean hackney"
```

Will add more info shortly.

**Comment by robconery** [comment]
Which version of Elixir are you running?

**Comment by gmile** [comment]
@robconery I'm using `Elixir 1.4.0-dev (1db23c2)`, and erlang 19.0.2.

**Comment by robconery** [comment]
I would guess that's the problem then. You might want to check in with Hackney since it's the thing that won't compile.

**Comment by gmile** [comment]
Apparently this is the problem with [hackney / rebar](https://github.com/benoitc/hackney/issues/328), it seems. Runnin `mix local.rebar` (e.g. re-installing rebar) fixes it.

**Comment by wyattbenno777** [comment]
Great! I ran into the same issue today.
